#' @title Prepare Waves for Katharina's sync3d Engine
#' @description Generates the node data frame and the topological edge matrix for add_synchronized_3d_edges.
#' @param analysis_results The output list generated by the wave2lyze function.
#' @export
#' @importFrom plotly plot_ly
#' @import sync3d
prep_sync3d <- function(analysis_results) {
  # Generiert die Knotenpunkte und die topologische Kantenmatrix fuer add_synchronized_3d_edges.

  if (!is.list(analysis_results) || is.null(analysis_results$raw_coordinates)) {
    stop("Error: Invalid wave2lyze analysis results provided!")
  }

  # 1. Extract node points (Coordinates)
  # 1. Knotenpunkte (Nodes) extrahieren
  coords <- analysis_results$raw_coordinates
  n_points <- nrow(coords)

  nodes_df <- data.frame(
    x = coords[, 1],
    y = coords[, 2],
    z = analysis_results$wave_amplitudes
  )

  # 2. Generate edge matrix for a continuous synchronized line
  # 2. Kantenmatrix (Edges) generieren fuer fortlaufende Linien
  from_indices <- 1:(n_points - 1)
  to_indices <- 2:n_points
  edge_matrix <- matrix(c(from_indices, to_indices), ncol = 2, byrow = FALSE)

  message("Bridge to sync3d established: Nodes and edges successfully generated!")

  return(list(
    nodes = nodes_df,
    edges = edge_matrix
  ))
}
